version: '3'

services:
  rabbitmq:
    build:
      dockerfile: Dockerfile.rabbitmq_custom
    container_name: rabbitmq-custom
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
